//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.235
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd 自动生成, Version=4.0.30319.1。
// 
namespace MiniTwitter.Net.Twitter {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class media : PropertyChangedBase {
        
        private mediaCreative[] creativeField;
        
        /// <remarks/>
        [XmlElement("creative")]
        public mediaCreative[] creative {
            get {
                return this.creativeField;
            }
            set {
                this.creativeField = value;
                OnPropertyChanged("creative");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class mediaCreative : PropertyChangedBase {
        
        private string typeField;
        
        private string media_urlField;
        
        private string expanded_urlField;
        
        private string display_urlField;
        
        private string media_url_httpsField;
        
        private string id_strField;
        
        private mediaCreativeSizes sizesField;
        
        private string urlField;
        
        private ulong idField;
        
        private int endField;
        
        private int startField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                OnPropertyChanged("type");
            }
        }
        
        /// <remarks/>
        public string media_url {
            get {
                return this.media_urlField;
            }
            set {
                this.media_urlField = value;
                OnPropertyChanged("media_url");
            }
        }
        
        /// <remarks/>
        public string expanded_url {
            get {
                return this.expanded_urlField;
            }
            set {
                this.expanded_urlField = value;
                OnPropertyChanged("expanded_url");
            }
        }
        
        /// <remarks/>
        public string display_url {
            get {
                return this.display_urlField;
            }
            set {
                this.display_urlField = value;
                OnPropertyChanged("display_url");
            }
        }
        
        /// <remarks/>
        public string media_url_https {
            get {
                return this.media_url_httpsField;
            }
            set {
                this.media_url_httpsField = value;
                OnPropertyChanged("media_url_https");
            }
        }
        
        /// <remarks/>
        public string id_str {
            get {
                return this.id_strField;
            }
            set {
                this.id_strField = value;
                OnPropertyChanged("id_str");
            }
        }
        
        /// <remarks/>
        public mediaCreativeSizes sizes {
            get {
                return this.sizesField;
            }
            set {
                this.sizesField = value;
                OnPropertyChanged("sizes");
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                OnPropertyChanged("url");
            }
        }
        
        /// <remarks/>
        public ulong id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                OnPropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                OnPropertyChanged("end");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                OnPropertyChanged("start");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class mediaCreativeSizes : PropertyChangedBase {
        
        private mediaCreativeSizesMedium mediumField;
        
        private mediaCreativeSizesSmall smallField;
        
        private mediaCreativeSizesLarge largeField;
        
        private mediaCreativeSizesThumb thumbField;
        
        /// <remarks/>
        public mediaCreativeSizesMedium medium {
            get {
                return this.mediumField;
            }
            set {
                this.mediumField = value;
                OnPropertyChanged("medium");
            }
        }
        
        /// <remarks/>
        public mediaCreativeSizesSmall small {
            get {
                return this.smallField;
            }
            set {
                this.smallField = value;
                OnPropertyChanged("small");
            }
        }
        
        /// <remarks/>
        public mediaCreativeSizesLarge large {
            get {
                return this.largeField;
            }
            set {
                this.largeField = value;
                OnPropertyChanged("large");
            }
        }
        
        /// <remarks/>
        public mediaCreativeSizesThumb thumb {
            get {
                return this.thumbField;
            }
            set {
                this.thumbField = value;
                OnPropertyChanged("thumb");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class mediaCreativeSizesMedium : PropertyChangedBase {
        
        private int wField;
        
        private int hField;
        
        private string resizeField;
        
        /// <remarks/>
        public int w {
            get {
                return this.wField;
            }
            set {
                this.wField = value;
                OnPropertyChanged("w");
            }
        }
        
        /// <remarks/>
        public int h {
            get {
                return this.hField;
            }
            set {
                this.hField = value;
                OnPropertyChanged("h");
            }
        }
        
        /// <remarks/>
        public string resize {
            get {
                return this.resizeField;
            }
            set {
                this.resizeField = value;
                OnPropertyChanged("resize");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class mediaCreativeSizesSmall : PropertyChangedBase {
        
        private int wField;
        
        private int hField;
        
        private string resizeField;
        
        /// <remarks/>
        public int w {
            get {
                return this.wField;
            }
            set {
                this.wField = value;
                OnPropertyChanged("w");
            }
        }
        
        /// <remarks/>
        public int h {
            get {
                return this.hField;
            }
            set {
                this.hField = value;
                OnPropertyChanged("h");
            }
        }
        
        /// <remarks/>
        public string resize {
            get {
                return this.resizeField;
            }
            set {
                this.resizeField = value;
                OnPropertyChanged("resize");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class mediaCreativeSizesLarge : PropertyChangedBase {
        
        private int wField;
        
        private int hField;
        
        private string resizeField;
        
        /// <remarks/>
        public int w {
            get {
                return this.wField;
            }
            set {
                this.wField = value;
                OnPropertyChanged("w");
            }
        }
        
        /// <remarks/>
        public int h {
            get {
                return this.hField;
            }
            set {
                this.hField = value;
                OnPropertyChanged("h");
            }
        }
        
        /// <remarks/>
        public string resize {
            get {
                return this.resizeField;
            }
            set {
                this.resizeField = value;
                OnPropertyChanged("resize");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class mediaCreativeSizesThumb : PropertyChangedBase {
        
        private int wField;
        
        private int hField;
        
        private string resizeField;
        
        /// <remarks/>
        public int w {
            get {
                return this.wField;
            }
            set {
                this.wField = value;
                OnPropertyChanged("w");
            }
        }
        
        /// <remarks/>
        public int h {
            get {
                return this.hField;
            }
            set {
                this.hField = value;
                OnPropertyChanged("h");
            }
        }
        
        /// <remarks/>
        public string resize {
            get {
                return this.resizeField;
            }
            set {
                this.resizeField = value;
                OnPropertyChanged("resize");
            }
        }
    }
}
